language: R
sudo: false
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
env:
  global:
    secure: oFIVr4F1yprvnzKM1HLcrPPhCtTWG4FGFtUTlhDOcNAyjbSen2BYdHYA7Pja1MaqGgkA/d30c6uRkqt3NXiOhivM07zPyk37hO+pdWxLQSmBo0xbYma61DndgAY7k72KHw3aNAhZHX8b4CDIJq3naA3jTHFM7mOBGf/YY/WT5HsKv94kNBvyw2nYumrwyA4HLIdDSZi3A2iTKdlRhNCKTzc3cHi7iDXXen1rPmvTSAIkwANvwKZn8ybUSkqD91n6LVguVAKM5eFw2jUDZJHPnlSb9xGRlS1mHuQveKT9HAmbTu2AKSsFePj3RqxrS5c0cNhQJxR3mINnONtzGknQsRCxYmlNZrsp4O2aVx3uDXpR/6shPuHjdF1au4M3coo1vIyHJjqRF9sKiNfPukfO2kmK9g86Ueyu1EV23nHVQOXmt1atL0AaDkp9BZCcsz0c7d91+wvugdgZOj6BLmbwmSBuInZg28TYZoNV9gpMXQ5GjamwyUirwuQ2+Y//cAUVNgUK9rVwJajVFV6yl/K4gpCQfgL86oFBWzrVGzxUWVrWoviJYIzG0F2ZHSmnxRPZCnPFfWFXKPWkf08EhFKM6I+exXRjEdtM1yAJodlDrhyILYUszmjw+9dNWc7geeciAJJWd8Ll8MpB1zyp0RsPVyhko5E+g3YPwHizKt39d+U=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _deploy.sh
