language: R
sudo: false
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
env:
  global:
    secure: ozMzcp5ckkrZ7010nCREr6PuZvp4xZlt9rNVyyzietFqnUs+zTCHCCGskAhhmCExaFcAvPh1BaUJfuS+Cbss64RAhxhFxheoMc9G8hzXU0hzH2LohTu+m5Md97GdRRIhoPjlnnWLpJD3HJyZlDNmB0TEwKM31tOSQmE7d2aKQXtcncQ0QB0cFLS6q4mvp1bEfPR6fJteA5zH48GncL8efpJl0RWSVdrvzU6PjB1f7xD5i7SprgwzDiK/hlG5OeG6WJvjigIeHOIY1MlNWoQNCSB190ppzgp5XdSWHQN4hCD+AE3D/Uc6H8dcyo4Gfdu6DEtYshcUZuMizsL2X831cgWzPVQAwlBRZceecrVv54FieFo9HFH/qthtLwYMm5WiMPW8pqai/QjekhIB9q5lwSbA8svbVr27k5GV+OAvxYFkaV62s2llD9SNuBi4+aXCtYqfQxVM+ojPzIrXEe8A6Ic+7eOjRRF+gWnbo7adq5MQEextjjT7aowQ7KSLqWhTHPddX9z0rgKHRs8lLXiVekQN2X6ejOwbz+/nSEgAgbL8kN8F71/3psGRQW5JQbq8c1oUWbuwKrblXtHFEBGU0+LHCe2zPkhl3xaBDiQj8ZlezrKFpkD9B7KcEozIms3qsWDgw0LLuy1H5n1YXcVDnltpriowcSAj/YHPZnl5OdA=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _deploy.sh
